name: Make Scripts Executable

on:
  push:
    paths:
      - 'scripts/*.sh'
  workflow_dispatch:

jobs:
  update-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/*.sh
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add scripts/*.sh
          git diff --staged --quiet || git commit -m "Make scripts executable"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main